import type { HttpContext } from '@adonisjs/core/http'
import User from '#models/user'
import hash from '@adonisjs/core/services/hash'
import exceljs from 'exceljs'
import PDFDocument from 'pdfkit'
import { DateTime } from 'luxon'

export default class AuthController {
  async register({ request, response }: HttpContext) {
    const data = request.only(['email', 'password', 'fullName']) 
    const user = await User.create({
      ...data,
    })

    const token = await User.accessTokens.create(user)

    return response.ok({
      type: 'bearer',
      token: token.value!.release(),  
      expires_at: token.expiresAt,
    })
  }

  async login({ request, response }: HttpContext) {
    const { email, password } = request.only(['email', 'password'])
    const user = await User.findBy('email', email)

    if(!user){
        return response.unauthorized({ message: "Email is not found"})
    }

    const isValid = await hash.verify(user.password, password)

    if(!isValid){
        return response.unauthorized({message: "Invalid Password"})
    }

    const token = await User.accessTokens.create(user)

    return response.ok({
      type: 'bearer',
      token: token.value!.release(),  
      expires_at: token.expiresAt,
      user:user
    })
  }


async logout({ auth, response }: HttpContext) {
  const user = auth.getUserOrFail()  

  if (!user.currentAccessToken) {
    return response.ok({ message: 'Already logged out or invalid token' })
  }

  const tokenId = user.currentAccessToken.identifier
  await User.accessTokens.delete(user, tokenId)

  return response.ok({ message: 'Logged out successfully' })
}
  async me({ auth,response }: HttpContext) {
      const user = auth.getUserOrFail()     
      console.log(auth.user);
  return response.json({
    message: "User is authenticated",
    data: user,
  })
}
  async exportAllUsersPdf({ auth, response }: HttpContext) {
  // const currentUser = auth.getUserOrFail()

  const users = await User.query()
    .orderBy('created_at', 'desc')
    .select('id', 'full_name', 'email', 'created_at', 'updated_at')

  if (users.length === 0) {
    return response.notFound({ message: 'Koi users nahi mile database mein' })
  }



  const doc = new PDFDocument({ margin: 50, size: 'A4', layout: 'portrait' })

  response.header('Content-Type', 'application/pdf')
  response.header(
    'Content-Disposition',
    `attachment; filename=All_Users_${DateTime.now().toFormat('dd-MM-yyyy')}.pdf`
  )
response.stream(doc)

  doc
    .fontSize(22)
    .text('All Registered Users', { align: 'center' })
    .moveDown(0.5)
   
    .fontSize(12)
    .text(`Total Users: ${users.length}`, { align: 'center' })
    .moveDown(2)

  const tableTop = doc.y
  doc
    .fontSize(11)
    .text('ID', 50, tableTop)
    .text('Full Name', 100, tableTop)
    .text('Email', 250, tableTop)
    .text('Registered On', 400, tableTop)

  doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).lineWidth(1).stroke()

  let yPosition = tableTop + 25
  let pageCount = 1

  for (const [index, user] of users.entries()) {
    if (yPosition > 700) {
      doc.addPage()
      yPosition = 50
      pageCount++
    }

    doc
      .fontSize(10)
      .text(user.id.toString(), 50, yPosition)
      .text(user.fullName || 'N/A', 100, yPosition, { width: 140 })
      .text(user.email, 250, yPosition, { width: 140 })
      .text(user.createdAt.toFormat('dd-MM-yyyy hh:mm a'), 400, yPosition)

    yPosition += 20

    if ((index + 1) % 10 === 0) {
      doc.moveTo(50, yPosition).lineTo(550, yPosition).lineWidth(0.3).stroke()
      yPosition += 10
    }
  }

  doc
    .moveDown(3)
    .fontSize(9)
    .text('Generated by Your App Name', { align: 'center' })
    .text(`Total Users: ${users.length} | Pages: ${pageCount}`, { align: 'center' })

  doc.end()

  return response
}

public async exportexcel({ response }: HttpContext){  
    const users = await User.all()

    const workbook = new exceljs.Workbook()
    const worksheet = workbook.addWorksheet('Users')

    worksheet.columns = [
      { header: 'ID', key: 'id', width: 10 },
      { header: 'Name', key: 'name', width: 30 },
      { header: 'Email', key: 'email', width: 30 },
    ]

    users.forEach((user) => {
      worksheet.addRow({
        id: user.id,
        name: user.fullName,
        email: user.email,
      })
    })

    worksheet.getRow(1).font = { bold: true }

    const buffer = await workbook.xlsx.writeBuffer()

    response.header('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response.header('Content-Disposition', 'attachment; filename=users.xlsx')
    
    return response.send(buffer)
  }
}
